# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-09-07T21:46:45Z"
  labels:
    app: clean-arch
  name: clean-arch
spec:
  containers:
    - args:
        - mysqld
      image: docker.io/library/mysql:5.7
      name: mysql
      ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 50051
          hostPort: 50051
        - containerPort: 8000
          hostPort: 8000
        - containerPort: 5672
          hostPort: 5672
        - containerPort: 15672
          hostPort: 15672
        - containerPort: 3306
          hostPort: 3306
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: home-rodrigo-projects-golang-expert-desafio-clean-architecture-.docker-mysql-host-0
    - args:
        - rabbitmq-server
      image: docker.io/library/rabbitmq:3-management
      name: rabbitmq
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: beac9324f556265634b662e109aaad3d37df80df2bcfe5167859e677abecb60e-pvc
    - image: localhost/rodrigoafernandes/golang-expert/desafio-clean-architecture:0.0.1
      name: desafio-clean-architecture
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
  restartPolicy: Always
  volumes:
    - name: beac9324f556265634b662e109aaad3d37df80df2bcfe5167859e677abecb60e-pvc
      persistentVolumeClaim:
        claimName: beac9324f556265634b662e109aaad3d37df80df2bcfe5167859e677abecb60e
    - hostPath:
        path: /home/rodrigo/projects/golang-expert/desafio-clean-architecture/.docker/mysql
        type: Directory
      name: home-rodrigo-projects-golang-expert-desafio-clean-architecture-.docker-mysql-host-0
status: {}

